version: "2"
services:
  server-java:
    container_name: odatajavaservice-external
    image: tomcat:jdk8-adoptopenjdk-openj9
    volumes:
    - ./webapps:/usr/local/tomcat/webapps/
    depends_on:
    - web
    ports:
    - "8080:8080"
    command: bash catalina.sh run
  web:
    build: .
    ports:
      - "3005:3005"
    depends_on:
      - db
  db:
    container_name: "mongo-db"
    image: mongo
    ports: 
      -  "3001:27017"
